"""
export_utils.py
---------------
Saving and exporting analysis results.

Provides:
  - append_history()  : log every analysis to history/history.csv
  - load_history()    : read the history back as a list of dicts
  - export_csv()      : single result -> CSV bytes (for download button)
  - export_pdf()      : single result -> PDF bytes (for download button)

Kept dependency-light: PDF uses reportlab (in requirements.txt).

Author: Voice AI System
"""

import os
import csv
import io
from datetime import datetime

HISTORY_DIR = "history"
HISTORY_FILE = os.path.join(HISTORY_DIR, "history.csv")
os.makedirs(HISTORY_DIR, exist_ok=True)

# Column order used in the history CSV.
FIELDS = [
    "timestamp", "filename", "gender", "gender_conf",
    "age_group", "age_conf", "emotion", "emotion_conf",
    "pitch_hz", "pitch_band", "speaking_rate", "speech_ratio",
]


def _flatten(result, filename):
    """Turn a nested analysis dict into one flat row for CSV/history."""
    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "filename": filename,
        "gender": result["gender"]["value"],
        "gender_conf": round(result["gender"]["confidence"], 3),
        "age_group": result["age"]["value"],
        "age_conf": round(result["age"]["confidence"], 3),
        "emotion": result["emotion"]["value"],
        "emotion_conf": round(result["emotion"]["confidence"], 3),
        "pitch_hz": result["pitch"]["hz"],
        "pitch_band": result["pitch"]["band"],
        "speaking_rate": result["speaking_rate"]["label"],
        "speech_ratio": result["speech_ratio"],
    }


def append_history(result, filename):
    """Append one analysis to the persistent history CSV."""
    row = _flatten(result, filename)
    file_exists = os.path.exists(HISTORY_FILE)
    with open(HISTORY_FILE, "a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)
    return row


def load_history():
    """Return the full history as a list of dict rows (newest last)."""
    if not os.path.exists(HISTORY_FILE):
        return []
    with open(HISTORY_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def clear_history():
    """Delete the history CSV, resetting to an empty state."""
    if os.path.exists(HISTORY_FILE):
        os.remove(HISTORY_FILE)


def export_csv(result, filename):
    """Return CSV bytes for a single analysis (used by st.download_button)."""
    row = _flatten(result, filename)
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=FIELDS)
    writer.writeheader()
    writer.writerow(row)
    return buf.getvalue().encode("utf-8")


def export_pdf(result, filename):
    """
    Return PDF bytes summarising a single analysis.

    Uses reportlab. If reportlab is not installed, raises a clear error.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.pdfgen import canvas
    except ImportError as e:
        raise ImportError(
            "reportlab is required for PDF export. "
            "Install it with: pip install reportlab"
        ) from e

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    y = height - 2 * cm
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2 * cm, y, "AI Voice Analysis Report")

    y -= 1 * cm
    c.setFont("Helvetica", 10)
    c.drawString(2 * cm, y, f"File: {filename}")
    y -= 0.6 * cm
    c.drawString(2 * cm, y, f"Generated: {datetime.now():%Y-%m-%d %H:%M:%S}")

    # Body lines.
    lines = [
        ("Gender", f"{result['gender']['value']} "
                   f"({result['gender']['confidence']*100:.1f}%)"),
        ("Age Group", f"{result['age']['value']} {result['age'].get('range','')} "
                      f"({result['age']['confidence']*100:.1f}%)"),
        ("Emotion", f"{result['emotion']['value']} "
                    f"({result['emotion']['confidence']*100:.1f}%)"),
        ("Pitch", f"{result['pitch']['hz']} Hz ({result['pitch']['band']})"),
        ("Speaking Rate", f"{result['speaking_rate']['label']} "
                          f"({result['speaking_rate']['syllables_per_sec']} syl/s)"),
        ("Speech Ratio", str(result["speech_ratio"])),
    ]

    y -= 1.2 * cm
    for label, value in lines:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, f"{label}:")
        c.setFont("Helvetica", 12)
        c.drawString(6 * cm, y, value)
        y -= 0.8 * cm

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2 * cm, 1.5 * cm,
                 "Generated by AI Voice Analysis System")
    c.showPage()
    c.save()
    buf.seek(0)
    return buf.getvalue()
